name: Staging Continuous Delivery

on:
  push:
    branches:
      - develop

env:
  HEROKU_BACKEND_APP_NAME: prettythings-backend
  HEROKU_WEB_APP_NAME: prettythings-web

jobs:
  build_push_backend:
    name: Build and Push Backend Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cd graphql-backend
          docker build -t demo-prettythings-backend -f Dockerfile.heroku .
          docker tag demo-prettythings-backend registry.heroku.com/$HEROKU_BACKEND_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_BACKEND_APP_NAME/web
  build_push_web:
    name: Build and Push Web Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cd web
          docker build -t demo-prettythings-web -f Dockerfile.heroku .
          docker tag demo-prettythings-web registry.heroku.com/$HEROKU_WEB_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_WEB_APP_NAME/web
  release_both:
    name: Release Web and Backend Container
    runs-on: ubuntu-latest
    needs: [build_push_backend, build_push_web]
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Release web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a $HEROKU_WEB_APP_NAME web
      - name: Release backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a $HEROKU_BACKEND_APP_NAME web
